- name: Docker install and configuration
  hosts: servers
  become: true
  roles: 
    - geerlingguy.docker

- name: install docker sdk
  hosts: servers
  become: true
  tasks: 
    - name: Install pip
      package:
        name: python3-pip
        state: present

    - name: Install docker sdk
      pip:
        name: docker

- name: Postgre Database configuration
  hosts: postgresql
  become: true
  roles:
    - postgre
- name: Nodejs server configuration
  hosts: nodejs
  become: true
  roles:
    - nodejs
- name: React UI Server configuration
  hosts: react
  become: true
  roles:
    - react