AWSTemplateFormatVersion: 2010-09-09
Description: |
  This CloudFormation Template was written for Decimal to Romans converter Static Website on EC2. Decimal to Romans converter Static Website will be deployed on Amazon Linux 2 (ami-02e136e904f3da870) EC2 Instance with custom security group which allows http connections on port 80 and ssh port 22 from anywhere. Decimal to Romans converter Static Website 
  is downloaded from my Public Github repository, then deployed on Apache Web Server.
  

Resources:
  Mysg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP for Apache webserver and SSH for secure connection # Required
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  Myserver:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-02e136e904f3da870
      InstanceType: t2.micro
      KeyName: third_key
      SecurityGroupIds:
        - !Ref Mysg
      Tags:
        - Key: Name
          Value: !Sub Web Server of ${AWS::StackName}
      UserData: 
        Fn::Base64:
          !Sub |
            #!/bin/bash
            sudo yum update -y
            sudo yum install git -y
            sudo pip3 install flask
            sudo git clone https://github.com/skoc10/my_projects.git 
            sudo cd /home/ec2-user
            sudo mkdir python
            cd python/
            sudo cp -R /my_projects/aws/Project2-Roman-Numerals-Converter/* .
            sudo python3 roman_alphabet.py


Outputs:
  WebsiteURL:
    Value: !Sub
      - http://${PublicAddress}
      - PublicAddress: !GetAtt Myserver.PublicDnsName 
    Description: Decimal to Romans Calculator