  
Resources:
  myinstance:
    Type: AWS::EC2::Instance
    Properties:
      
      AvailabilityZone: us-east-1a
      
      ImageId: ami-02e136e904f3da870
      InstanceInitiatedShutdownBehavior: "String"
      InstanceType: t2.micro
      
      SecurityGroups:
        - !Ref SSHSG
        - !Ref ServerSG 
      
  MYeip:
    Type: AWS::EC2::EIP
    Properties:  
      InstanceId: !Ref myinstance

  SSHSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ilk sg icin olusturulu # Required
      GroupName: ilksg
      SecurityGroupIngress:
        - IpProtocol: tcp 
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      
  ServerSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ikinci sg icin # Required
      GroupName: ikincisg
      SecurityGroupIngress:
        - IpProtocol: tcp 
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp 
          FromPort: 80
          ToPort: 80
          CidrIp: 192.168.1.1/32
      